export enum ValidateArticleEditError {
  INCORRECT_TITLE = "INCORRECT_TITLE",
  INCORRECT_SUBTITLE = "INCORRECT_SUBTITLE",
  INCORRECT_IMAGE_URL = "INCORRECT_IMAGE_URL",
  INCORRECT_BLOCKS_DATA = "INCORRECT_BLOCKS_DATA",
  NO_DATA = "NO_DATA",
  SERVER_ERROR = "SERVER_ERROR",
}

export const REG_EXP_IMAGE_URL: RegExp = new RegExp(/^https:\/\//);
