export enum ValidateUserEditError {
  INCORRECT_USER_DATA = "INCORRECT_USER_DATA",

  INCORRECT_EMAIL = "INCORRECT_EMAIL",

  INCORRECT_AVATAR = "INCORRECT_AVATAR",

  NO_DATA = "NO_DATA",
  SERVER_ERROR = "SERVER_ERROR",
}
